# Puerto del servidor
server.port=8080

# Conexion MySQL
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate

spring.servlet.multipart.max-file-size=10MB


# Mostrar SQL en consola
spring.jpa.show-sql=true

logging.level.org.springframework.security=TRACE
logging.level.org.hibernate=ERROR

# Dialecto MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect