INSERT INTO usuario
(nombre, apellido, email, password, telefono, documento, activo, role)
VALUES
    ('juan jose', 'sierra ortega', 'juan@gmail.com',
     '$2a$10$tZ5Zj5CmiCwCMQGOYGqKJOaNSRdVIDniSsk6wtS4qcSys0WOyFJF2',
     '1234567880','1112223344',true,'USER');

INSERT INTO evento (
    id_usuario,
    nombre,
    descripcion,
    categoria,
    lugar,
    ciudad,
    direccion,
    fecha_evento,
    fecha_creacion,
    capacidad,
    precio_base,
    estado
)
VALUES
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Afterlife Bogotá 2026',
        'Festival de música electrónica con artistas internacionales de techno melódico.',
        'CONCIERTO',
        'Parque Simón Bolívar',
        'Bogotá',
        'Av. Calle 63 #68-95',
        '2026-08-15 18:00:00',
        NOW(),
        18000,
        350000,
        'ACTIVO'
    ),
    (   (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Resistance Medellín',
        'Evento de techno underground con DJs internacionales.',
        'CONCIERTO',
        'Plaza Mayor',
        'Medellín',
        'Calle 41 #55-80',
        '2026-09-12 20:00:00',
        NOW(),
        12000,
        280000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Tomorrowland Unite Colombia',
        'Experiencia inspirada en el famoso festival belga de música electrónica.',
        'CONCIERTO',
        'Centro de Eventos Valle del Pacífico',
        'Cali',
        'Yumbo',
        '2026-11-07 16:00:00',
        NOW(),
        25000,
        450000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Techno Warehouse Session',
        'Noche de techno industrial en una locación tipo warehouse.',
        'CONCIERTO',
        'Distrito Industrial',
        'Bogotá',
        'Zona Industrial Fontibón',
        '2026-07-18 22:00:00',
        NOW(),
        3500,
        180000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Black Coffee Live',
        'Presentación especial del reconocido DJ sudafricano Black Coffee.',
        'CONCIERTO',
        'Movistar Arena',
        'Bogotá',
        'Diagonal 61C #26-35',
        '2026-10-03 20:00:00',
        NOW(),
        14000,
        320000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Carl Cox Revolution',
        'Show de techno y house con uno de los DJs más influyentes del mundo.',
        'CONCIERTO',
        'Centro de Convenciones',
        'Cartagena',
        'Getsemaní',
        '2026-12-05 21:00:00',
        NOW(),
        10000,
        390000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Boiler Room Bogotá',
        'Experiencia inmersiva de música electrónica con artistas locales e internacionales.',
        'CONCIERTO',
        'Corferias',
        'Bogotá',
        'Carrera 37 #24-67',
        '2026-06-20 19:00:00',
        NOW(),
        7000,
        220000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Medellín Electronic Festival',
        'Festival de techno, house y melodic techno con múltiples escenarios.',
        'CONCIERTO',
        'Parque Norte',
        'Medellín',
        'Cra. 53 #76-115',
        '2026-08-29 15:00:00',
        NOW(),
        16000,
        260000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Underground Techno Night',
        'Sesión nocturna enfocada en techno oscuro y minimal.',
        'CONCIERTO',
        'Club Industrial',
        'Barranquilla',
        'Cra. 51B #79-97',
        '2026-09-26 23:00:00',
        NOW(),
        2500,
        150000,
        'ACTIVO'
    ),
    (
        (SELECT id FROM usuario WHERE email = 'juan@gmail.com'),
        'Adriatique Experience',
        'Evento exclusivo con el dúo suizo Adriatique y artistas invitados.',
        'CONCIERTO',
        'Centro de Eventos Autopista Norte',
        'Bogotá',
        'Autopista Norte Km 19',
        '2026-11-21 18:00:00',
        NOW(),
        9000,
        340000,
        'ACTIVO'
    );

INSERT INTO events_photos (event_id, link)
VALUES
    (1, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-5X2pqV1Z3COHAaPyzuh-t6uPTKA2NTMjKODm4dkUBdre1HyVAyYwF4Q&s=10'),
    (1, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR0vF9KztBa-qwADAy6NgGKUyfeV0s0ArH2ikmhj255h2xokwIx74s7_i2&s=10'),
    (1,'https://www.decodedmagazine.com/wp-content/uploads/2018/09/Hernan-Connected-1-Decoded-Magazine-672x372.jpg'),
    (2,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvOvj3zBQZu3_l7MDCmcsU5DESRJFuviOh9K-nQSVy2ZeImcHY9D45dA&s=10'),
    (2,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyeW5OUd0ZRtxB4izTp2i1MzvUDQEno6oU0QHJmGOC3H9PVotTqzGiQEvJ&s=10'),
    (2,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfsNcB2qeFYKYOVsOeo8-ikJ2fw9-Ni2v_6E_klFRLch2IRc5LJ7DF5Ko&s=10'),
    (3,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRFxZ11wduGJ6JSJDL06RcHvYImSo8bmfOP4An-qZk5ykJSoWQufn1OrA&s=10'),
    (4,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV9Jf2cReTkpWMef_22djqkfL5QXTgSNO3WzCSnnKZVPjLk3gKrzETekA&s=10'),
    (4,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDBK_tos9aK90tKfaPFO-JuIr_KGcGfCYvSqZwHWOqplJBbw7bAl-wFv5N&s=10'),
    (5,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToE0jvCWGiCCyCRYIyI4ezqel3vJiXQ8tSJgeIoPFraCNkS7arR0cEXHY&s=10'),
    (5,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjKC5-CODEtXyyerzKyH0gvniSZn3Yi60e2Ib3pqhXz3jseIk2xQMbwjM&s=10'),
    (6,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-asx8h_rmE-hTGgxp4By9rsHwKh7pMRiDu55qJ5rX3JAlEx9QhWQD_d4&s=10'),
    (6,'https://i2-prod.irishmirror.ie/article28707267.ece/ALTERNATES/s1200f/3_CCW-48.jpg'),
    (6,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgIizbr3wW8WbvjOSStoLjaHCrMMj6G6gtmAL2jt1hwzNUYkWL17jlR14&s=10'),
    (7,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjyKjnk2FEGAK2Rrh0LDaO3g3WsZTi2hOY1Lyhzyfuj9wQ3fVdkmCGI_I&s=10'),
    (7,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrj3nZ7FS_wyWuB27CmZae8ccPVcvdOG0QTiOkMo0Qqr-hxa51h5_njjg&s=10'),
    (8,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTktZeVD3AbAckL4mkWdI4FUUq1YQRZN8IUiz78uPO50g&s=10'),
    (8,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoHCtSLeg7yKdzCOAdHzTH45oIP2l7NlIcMJeiPbag4DS_R9JMjTz8bthP&s=10'),
    (9,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrj3nZ7FS_wyWuB27CmZae8ccPVcvdOG0QTiOkMo0Qqr-hxa51h5_njjg&s=10'),
    (9,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrj3nZ7FS_wyWuB27CmZae8ccPVcvdOG0QTiOkMo0Qqr-hxa51h5_njjg&s=10'),
    (9,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuIz2OFSu2RMEqq06piO80jtvZmtqle_p_zpUI3pEQEoyPnmO_Cvh5xRg&s=10');


